language: java

dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

jdk:
  - oraclejdk8

script:
  - mvn clean verify

cache:
  directories:
    - '$HOME/.m2/repository'